// Practice/Frontend/google-maps-react/src/App.jsx
import React, { useEffect, useState } from "react";

import { GoogleMap, LoadScript, Marker } from "@react-google-maps/api";

const containerStyle = {
  width: "400px",
  height: "400px",
};

const center = {
  lat: 37.7749, // San Francisco, CA
  lng: -122.4194,
};



function App() {
  return (
    <>
      <LoadScript googleMapsApiKey="AIzaSyDkGNFruQqakgT_on4HEhdbLStuLvEAd3E">
        <GoogleMap mapContainerStyle={containerStyle} center={center} zoom={12}>
          <Marker position={center} />
        </GoogleMap>
      </LoadScript>
    </>
  );
}

export default App;

// Practice/google-maps-vue/src/App.vue
<template>
  <GoogleMap api-key="AIzaSyDkGNFruQqakgT_on4HEhdbLStuLvEAd3E" style="width: 100%; height: 500px" :center="center"
    :zoom="15">
    <Marker :options="{ position: center }" />
  </GoogleMap>
</template>

<script>
import { defineComponent } from "vue";
import { GoogleMap, Marker } from "vue3-google-map";

export default defineComponent({
  components: { GoogleMap, Marker },
  setup() {
    const center = { lat: 40.689247, lng: -74.044502 };

    return { center };
  },
});
</script>
